--CREATE EXTENSION IF NOT EXISTS pgcrypto; --only need this if pgcrypto isn't already downloaded

CREATE TABLE PendingRegistration(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL,
    -- REGISTRATION_TOKEN VARCHAR(50) NOT NULL UNIQUE,
    -- EXPIRATION_DATE TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NEW_EMAIL TEXT NULL,
    NEW_PHONE_NUMBER TEXT NULL,
	FOREIGN KEY (USER_ID) REFERENCES users(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER update_pending_registration_updated_at 
    BEFORE UPDATE ON PendingRegistration
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

--CREATE TABLE PendingRegistrationLookup(
--    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--    PENDING_REGISTRATION_ID UUID NOT NULL UNIQUE,
--    REGISTRATION_TOKEN VARCHAR(50) NOT NULL UNIQUE,
--    FOREIGN KEY (PENDING_REGISTRATION_ID)
--        REFERENCES PendingRegistration(ID)
--        ON DELETE CASCADE
--        ON UPDATE CASCADE
--);
